// Host tests for input_parsers.h. The E1.31 reference packet was generated by the independent Python
// `sacn` library (DataPacket, universe 3, source "xLights", slots FF 00 80 ... 11), truncated to 10 slots.
// Run: pio test -e native
#include <unity.h>

#include <cstring>
#include <string>
#include <vector>

#include "input_parsers.h"

using namespace bracelet;

static std::vector<uint8_t> from_hex(const std::string &hex) {
    std::vector<uint8_t> out;
    for (size_t i = 0; i + 1 < hex.size(); i += 2)
        out.push_back((uint8_t) std::stoul(hex.substr(i, 2), nullptr, 16));
    return out;
}

// 126-byte header + 10 slots. Property count in the header still says 513 (full universe).
static const char *SACN_REF =
    "001000004153432d45312e3137000000726e00000004000102030405060708090a0b0c0d0e0f725800000002784c6967"
    "687473000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    "00000000000000000000000064000007000003720b02a100000001020100ff008000000000000011";

void test_e131_reference_packet(void) {
    auto pkt = from_hex(SACN_REF);
    TEST_ASSERT_EQUAL(126 + 10, pkt.size());
    InputFrame f{};
    TEST_ASSERT_EQUAL((int) ParseResult::OK, (int) parse_e131(pkt.data(), pkt.size(), 3, f));
    TEST_ASSERT_EQUAL(0, f.offset);
    TEST_ASSERT_EQUAL(10, f.len);  // clamped to what was actually received
    TEST_ASSERT_TRUE(f.frame_end);
    const uint8_t expect[10] = {0xFF, 0x00, 0x80, 0, 0, 0, 0, 0, 0, 0x11};
    TEST_ASSERT_EQUAL_HEX8_ARRAY(expect, f.data, 10);
}

void test_e131_rejections(void) {
    auto pkt = from_hex(SACN_REF);
    InputFrame f{};
    TEST_ASSERT_EQUAL((int) ParseResult::IGNORED, (int) parse_e131(pkt.data(), pkt.size(), 1, f));  // other universe

    auto preview = pkt;
    preview[112] |= 0x80;
    TEST_ASSERT_EQUAL((int) ParseResult::IGNORED, (int) parse_e131(preview.data(), preview.size(), 3, f));

    auto terminated = pkt;
    terminated[112] |= 0x40;
    TEST_ASSERT_EQUAL((int) ParseResult::IGNORED, (int) parse_e131(terminated.data(), terminated.size(), 3, f));

    auto startcode = pkt;
    startcode[125] = 0xDD;  // RDM/ASC start code, not levels
    TEST_ASSERT_EQUAL((int) ParseResult::IGNORED, (int) parse_e131(startcode.data(), startcode.size(), 3, f));

    auto badid = pkt;
    badid[4] = 'X';
    TEST_ASSERT_EQUAL((int) ParseResult::MALFORMED, (int) parse_e131(badid.data(), badid.size(), 3, f));

    TEST_ASSERT_EQUAL((int) ParseResult::MALFORMED, (int) parse_e131(pkt.data(), 100, 3, f));
}

static std::vector<uint8_t> ddp(uint8_t flags, uint8_t id, uint32_t offset, std::vector<uint8_t> data,
                                bool timecode = false) {
    std::vector<uint8_t> p = {flags, 0x01, 0x0B, id, (uint8_t) (offset >> 24), (uint8_t) (offset >> 16),
                              (uint8_t) (offset >> 8), (uint8_t) offset, (uint8_t) (data.size() >> 8),
                              (uint8_t) data.size()};
    if (timecode)
        p.insert(p.end(), {0, 0, 0, 0});
    p.insert(p.end(), data.begin(), data.end());
    return p;
}

void test_ddp_basic(void) {
    auto p = ddp(0x41, 1, 3, {0x11, 0x22, 0x33});
    InputFrame f{};
    TEST_ASSERT_EQUAL((int) ParseResult::OK, (int) parse_ddp(p.data(), p.size(), f));
    TEST_ASSERT_EQUAL(3, f.offset);
    TEST_ASSERT_EQUAL(3, f.len);
    TEST_ASSERT_TRUE(f.frame_end);
    TEST_ASSERT_EQUAL_HEX8(0x22, f.data[1]);

    auto nopush = ddp(0x40, 1, 0, {1, 2, 3});
    parse_ddp(nopush.data(), nopush.size(), f);
    TEST_ASSERT_FALSE(f.frame_end);
}

void test_ddp_timecode_and_truncation(void) {
    auto p = ddp(0x51, 1, 0, {9, 8, 7}, true);
    InputFrame f{};
    TEST_ASSERT_EQUAL((int) ParseResult::OK, (int) parse_ddp(p.data(), p.size(), f));
    TEST_ASSERT_EQUAL_HEX8(9, f.data[0]);

    auto shortp = ddp(0x41, 1, 0, {1, 2, 3, 4, 5, 6});
    shortp.resize(shortp.size() - 2);  // header claims 6 bytes, only 4 arrived
    parse_ddp(shortp.data(), shortp.size(), f);
    TEST_ASSERT_EQUAL(4, f.len);
}

void test_ddp_rejections(void) {
    InputFrame f{};
    auto query = ddp(0x43, 1, 0, {});
    TEST_ASSERT_EQUAL((int) ParseResult::IGNORED, (int) parse_ddp(query.data(), query.size(), f));
    auto status = ddp(0x41, 251, 0, {1});
    TEST_ASSERT_EQUAL((int) ParseResult::IGNORED, (int) parse_ddp(status.data(), status.size(), f));
    auto badver = ddp(0x81, 1, 0, {1});
    TEST_ASSERT_EQUAL((int) ParseResult::MALFORMED, (int) parse_ddp(badver.data(), badver.size(), f));
    uint8_t tiny[5] = {0x41, 0, 0, 1, 0};
    TEST_ASSERT_EQUAL((int) ParseResult::MALFORMED, (int) parse_ddp(tiny, sizeof(tiny), f));
}

void setUp(void) {}
void tearDown(void) {}

int main(int, char **) {
    UNITY_BEGIN();
    RUN_TEST(test_e131_reference_packet);
    RUN_TEST(test_e131_rejections);
    RUN_TEST(test_ddp_basic);
    RUN_TEST(test_ddp_timecode_and_truncation);
    RUN_TEST(test_ddp_rejections);
    return UNITY_END();
}
