# Pre-build: gzip web/index.html into src/web_ui.h so the UI can be edited as a normal HTML file.
import gzip
import os

try:
    Import("env")  # noqa: F821
    project_dir = env.subst("$PROJECT_DIR")  # noqa: F821
except NameError:  # run directly: python3 tools/embed_ui.py
    project_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

src = os.path.join(project_dir, "web", "index.html")
dst = os.path.join(project_dir, "src", "web_ui.h")

with open(src, "rb") as f:
    html = f.read()
data = gzip.compress(html, compresslevel=9, mtime=0)

lines = []
for i in range(0, len(data), 20):
    lines.append("    " + ", ".join(f"0x{b:02x}" for b in data[i:i + 20]) + ",")
out = (
    "#pragma once\n"
    "// GENERATED by tools/embed_ui.py from web/index.html - do not edit.\n"
    "#include <Arduino.h>\n\n"
    f"static const size_t INDEX_HTML_GZ_LEN = {len(data)};\n"
    "static const uint8_t INDEX_HTML_GZ[] PROGMEM = {\n" + "\n".join(lines) + "\n};\n"
)
old = open(dst).read() if os.path.exists(dst) else None
if old != out:
    with open(dst, "w") as f:
        f.write(out)
print(f"web UI: {len(html)} bytes -> {len(data)} bytes gzipped")
